services:
  - type: web
    name: yoo-chat-server
    env: node
    plan: free
    region: oregon
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: "*"